### ISSUE TITLE
Support for ActiveRecord 6

### ISSUE THREAD

**Issue by Drenmi** [on-site/active_record-postgres-constraints#12]
Since Rails is now in beta2, it seems like a good time to add support. In the best case scenario, this involves just loosening the dependency. 😬

**Comment by betesh** [comment]
Opened #13 for this

**Comment by betesh** [comment]
released v0.1.5

**Comment by Drenmi** [comment]
Thank you for the response, @betesh. Looking forward to continuing using this with Rails 6. ❤️
