### ISSUE TITLE
Allowing custom constraints?

### ISSUE THREAD

**Issue by mcmire** [on-site/active_record-postgres-constraints#18]
Hey! I love the idea of this gem and would love to use it in our app at work. After playing around with it for a bit, I noticed that it doesn't allow you to place custom constraints on a table. It seems that when using `check_constraint`, you can only specify that a column must be one of a number of values. However, Postgres already provides this capability in the form of the ENUM type. Constraints are designed to be more powerful than this, as you can use any expression you want to check any column you want.

So, I have three questions:

1. What was the use case you were trying to solve in making this gem?
2. What do you think about making it possible to add custom constraints?
3. If I were to submit a PR, how should I extend your gem to do this?

**Comment by betesh** [comment]
>  you can only specify that a column must be one of a number of values.

Incorrect.  You can specify any condition as a String.  See https://github.com/on-site/active_record-postgres-constraints/blob/afb3277ca42ddd786a4702e99d27adb40aab1cd2/spec/active_record/postgres/constraints/types/check_spec.rb#L43 for example.

**Comment by ziaulrehman40** [comment]
I should be able to infer this from readme, please mention this possibility on the readme as well and save people like me a few minutes of searching. Thanks.

**Comment by betesh** [comment]
@ziaulrehman40 PR welcome.
