### ISSUE TITLE
RSpec Dummy app wants a Sprockets manifest.js

### ISSUE THREAD

**Issue by andrewclink** [on-site/active_record-postgres-constraints#23]
Following the directions in the readme results in Sprockets complaining about the lack of
`spec/dummy/app/assets/config/manifest.js`. 

This can be corrected by running

    mkdir -p spec/dummy/app/assets/config
    touch spec/dummy/app/assets/config/manifest.js

I can see a few solutions:
- Check this empty file into the repo
- Add it to `.gitignore` and update the readme.

**Comment by betesh** [comment]
Is it a warning or an error?  What versions of sprockets and rails?

**Comment by andrewclink** [comment]
It throws a `Sprockets::Railtie::ManifestNeededError` attempting to load the app environment. 

I used `bundle install` and it looks like it pulled in rails 6.0.1 and sprockets 4.0.0

[pg_ex.txt](https://github.com/on-site/active_record-postgres-constraints/files/3952006/pg_ex.txt)

**Comment by betesh** [comment]
Let me know if #24 fixes this
