### ISSUE TITLE
Please push 0.2 to rubygems

### ISSUE THREAD

**Issue by frsantos** [on-site/active_record-postgres-constraints#26]
Hi there, @betesh! 
Thanks for the gem. It's exactly what we need. Do you mind pushing version 0.2.0 to rubygems.org? We'd love to pull the new version from there, as it contains fixes that are relevant to us.

**Comment by betesh** [comment]
Done!

The reason I held off so long is that I was trying to weed out intermittent test failures caused by pg being async.  I'm still not sure that issue is gone, but it's been long enough that another release was overdue.

**Comment by frsantos** [comment]
Thanks!
