### ISSUE TITLE
Unique constraints (NOT indexes)?

### ISSUE THREAD

**Issue by suan** [on-site/active_record-postgres-constraints#35]
Thanks for writing this awesome gem!

Just checking, is there any plans for adding unique constraints?

**Comment by betesh** [comment]
Rails already offers a built-in, portable way to enforce uniqueness via indexes.  See https://stackoverflow.com/questions/23542794/postgres-unique-constraint-vs-index about the differences between uniqueness indeces and uniqueness constraints in postges.

I don't feel that adding a non-portable way to do something that there's already a portable way to do would add a benefit that justifies the cost of maintenance.

**Comment by betesh** [comment]
> Thanks for writing this awesome gem!

Thank you.  I appreciate the feedback :)
